// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackLowCodeTable: typeof import('./../src/components/TableExtra/BackLowCodeTable.vue')['default']
    CustomInputColumn: typeof import('./../src/components/CustomInputColumn/CustomInputColumn.vue')['default']
    CustomJsonInput: typeof import('./../src/components/CustomJsonInput.vue')['default']
    DbChooseExtractl: typeof import('./../src/components/TableExtra/DbChooseExtractl.vue')['default']
    DbChooseModal: typeof import('@/views/sql/DbChooseModal.vue')['default']
    DbChoosModal: typeof import('./../src/components/TableExtra/DbChoosModal.vue')['default']
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    FoldingCard: typeof import('./../src/components/FoldingCard.vue')['default']
    FrontLowCodeTable: typeof import('./../src/components/TableExtra/FrontLowCodeTable.vue')['default']
    InnerLink: typeof import('./../src/components/InnerLink/index.vue')['default']
    ParentView: typeof import('./../src/components/ParentView/index.vue')['default']
    RequestParams: typeof import('./../src/components/CustomInputColumn/RequestParams.vue')['default']
    ResponseParams: typeof import('./../src/components/CustomInputColumn/ResponseParams.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlFilterTable: typeof import('@/views/sql/SqlFilterTable.vue')['default']
    SqlLowCodeTable: typeof import('@/views/sql/SqlLowCodeTable.vue')['default']
    SqlTable: typeof import('./../src/components/TableExtra/SqlTable.vue')['default']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
    TemplateConfig: typeof import('./../src/components/TemplateConfig.vue')['default']
  }
}
