// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackLowCodeTable: typeof import('./../src/components/TableExtra/BackLowCodeTable.vue')['default']
    BasicInfo: typeof import('./../src/components/common/BasicInfo.vue')['default']
    ColumnGenerator: typeof import('./../src/components/common/ColumnGenerator.vue')['default']
    CustomInputColumn: typeof import('./../src/components/CustomInputColumn/CustomInputColumn.vue')['default']
    CustomJsonInput: typeof import('./../src/components/CustomJsonInput.vue')['default']
    DateAndFileExport: typeof import('./../src/components/common/DateAndFileExport.vue')['default']
    DBColumn: typeof import('./../src/components/common/DBColumn.vue')['default']
    DBColumnModal: typeof import('./../src/components/common/DBColumnModal.vue')['default']
    ElSvgIcon: typeof import('./../src/components/ElSvgIcon.vue')['default']
    FoldingCard: typeof import('./../src/components/FoldingCard.vue')['default']
    FrontLowCodeTable: typeof import('./../src/components/TableExtra/FrontLowCodeTable.vue')['default']
    InnerLink: typeof import('./../src/components/InnerLink/index.vue')['default']
    ParentView: typeof import('./../src/components/ParentView/index.vue')['default']
    RequestParams: typeof import('./../src/components/CustomInputColumn/RequestParams.vue')['default']
    ResponseParams: typeof import('./../src/components/CustomInputColumn/ResponseParams.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SqlBackTable: typeof import('./../src/components/common/SqlBackTable.vue')['default']
    SvgIcon: typeof import('./../src/icons/SvgIcon.vue')['default']
    TemplateConfig: typeof import('./../src/components/TemplateConfig.vue')['default']
  }
}
